// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20211019070523_NhanVien")]
    partial class NhanVien
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.NhanVien", b =>
                {
                    b.Property<string>("MSNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("TenNV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MSNV");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("WebApplication1.Models.TaiKhoan", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserName");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("WebApplication1.Models.TaiKhoan", b =>
                {
                    b.HasOne("WebApplication1.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("UserName");
                });
#pragma warning restore 612, 618
        }
    }
}
